processes:
  # - name: bolt
  #   module: bolt
  #   query: from:receipts@bolt.eu after:2024/01/01
  #   outputs:
  #     - type: stdout
  #       format: lines
  #     - type: file
  #       format: lines
  #       path: ./dump/bolt.txt
  #     - type: sheet
  #       format: csv
  #       path: Bolt data|||Hoja 1

  # - name: mmonit-encoders
  #   module: mmonit-encoders
  #   query: from:mmonit@aranova.cloud after:2024/05/01 before:2024/06/01
  #   outputs:
  #     # - type: stdout
  #     #   format: lines
  #     - type: file
  #       format: lines
  #       path: ./dump/mmonit-2024-05.txt
  #     - type: sheet
  #       format: csv
  #       path: Estadísticas codificación|||2024-May|||A4|||0

  # - name: mmonit-encoders
  #   module: mmonit-encoders
  #   query: from:mmonit@aranova.cloud after:2024/06/01 before:2024/07/01
  #   outputs:
  #     # - type: stdout
  #     #   format: lines
  #     - type: file
  #       format: lines
  #       path: ./dump/mmonit-2024-06.txt
  #     - type: sheet
  #       format: csv
  #       path: Estadísticas codificación|||2024-Jun|||A4|||0

  # - name: mmonit-encoders
  #   module: mmonit-encoders
  #   query: from:mmonit@aranova.cloud after:2024/07/01 before:2024/08/01
  #   outputs:
  #     # - type: stdout
  #     #   format: lines
  #     - type: file
  #       format: lines
  #       path: ./dump/mmonit-2024-07.txt
  #     - type: sheet
  #       format: csv
  #       path: Estadísticas codificación|||2024-Jul|||A4|||0

  # - name: mmonit-encoders
  #   module: mmonit-encoders
  #   query: from:mmonit@aranova.cloud after:2024/08/01 before:2024/09/01
  #   outputs:
  #     # - type: stdout
  #     #   format: lines
  #     - type: file
  #       format: lines
  #       path: ./dump/mmonit-2024-08.txt
  #     - type: sheet
  #       format: csv
  #       path: Estadísticas codificación|||2024-Ago|||A4|||0

  - name: mmonit-encoders
    module: mmonit-encoders
    query: from:mmonit@aranova.cloud after:2024/09/01 before:2024/10/01
    outputs:
      # - type: stdout
      #   format: lines
      - type: file
        format: lines
        path: ./dump/mmonit-2024-09.txt
      - type: sheet
        format: csv
        path: Estadísticas codificación|||2024-Sep|||A4|||0